# Generated by Django 3.1 on 2020-08-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200821_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_bith',
            new_name='date_of_birth',
        ),
    ]
