# Generated by Django 3.1 on 2020-08-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200822_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='lang',
            new_name='name',
        ),
    ]
